# Generated by Django 5.1.6 on 2025-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'verbose_name': 'Тип вопроса', 'verbose_name_plural': 'Типы вопросов'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='array_receivers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ'),
        ),
    ]
